# Generated by Django 3.2.8 on 2021-10-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_user_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
