# Generated by Django 3.2.8 on 2021-10-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_alter_user_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dni',
            field=models.IntegerField(default='38654734'),
            preserve_default=False,
        ),
    ]
