# Generated by Django 3.2.8 on 2021-10-14 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_user_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='inquilino',
        ),
        migrations.RemoveField(
            model_name='score',
            name='propietario',
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PermiteScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquilino_user', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='permitescore',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='permite_score', to='score.permitescore'),
            preserve_default=False,
        ),
    ]
