# Generated by Django 3.2.8 on 2021-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_auto_20211014_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitescore',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
