# Generated by Django 3.2.8 on 2021-10-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0008_permitescore_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
