# Generated by Django 3.2.8 on 2021-10-15 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0009_user_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='permitescore',
        ),
        migrations.AddField(
            model_name='score',
            name='inquilino',
            field=models.ForeignKey(default=(1), on_delete=django.db.models.deletion.CASCADE, related_name='inquilino_score', to='score.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='propietario',
            field=models.ForeignKey(default=(1), on_delete=django.db.models.deletion.CASCADE, related_name='propietario_score', to='score.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='average',
            field=models.IntegerField(default=0),
        ),
    ]
