# Generated by Django 3.2.8 on 2021-10-15 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0010_auto_20211015_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='desde',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='hasta',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='albums/images/'),
        ),
    ]
