# Generated by Django 3.2.8 on 2021-10-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0011_auto_20211015_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='hasta',
            field=models.DateField(),
        ),
    ]
