# Generated by Django 3.2.8 on 2021-10-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0012_auto_20211015_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='desde',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='score',
            name='hasta',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
