# Generated by Django 3.2.8 on 2021-10-15 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0014_auto_20211015_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
