# Generated by Django 3.2.8 on 2021-10-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0015_score_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.DateField(),
        ),
    ]
