# Generated by Django 3.2.8 on 2021-10-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0016_alter_score_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='desde',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='hasta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
