# Generated by Django 3.2.8 on 2021-10-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0018_auto_20211015_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.CharField(max_length=12),
        ),
    ]
