# Generated by Django 3.2.8 on 2021-10-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0020_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='score',
            name='comentario',
            field=models.CharField(max_length=400),
        ),
    ]
